### ISSUE TITLE
Cocoapods?

### ISSUE THREAD

**Issue by jlaws** [UrbanApps/Armchair#10]
cocoapods supports swift libraries now

**Comment by Dschee** [comment]
Any plans on this one from the project collaborators?

**Comment by Dschee** [comment]
I've tried to add Cocoapods support myself, see my pull request.

**Comment by Dschee** [comment]
Left to do:

* Add a section to README file with Cocoapods installation instructions
* Run `pod spec lint Armchair.podspec` to check for any errors
* Setup project with Cocoapods trunk (see [here](https://guides.cocoapods.org/making/getting-setup-with-trunk.html))

**Comment by DimaVartanian** [comment]
+1 Going to use UAAppReviewManager instead in the meantime just cause of that :(

**Comment by Alix-MICHEL** [comment]
+1

**Comment by vmouta** [comment]
+1

**Comment by coneybeare** [comment]
Cocoapod finally added! Sorry I took so long guys...
