### ISSUE TITLE
'No, thanks' is in Bold and at the bottom

### ISSUE THREAD

**Issue by ArturoLee** [UrbanApps/Armchair#100]
It seems that the 'No, thanks' AlertAction is in bold and is the last button on the AlertController. This is weird because the screen shots in library have 'No, thanks' as the first button, 'Remind me later' second, and 'Rate' last.

To me it makes more sense to have 'Rate' be the last button on the AlertController (like the screenshot).

We can just set the style for the **Rate** AlertAction to **UIAlertActionStyle.cancel**
And also set the style for the **Don't Rate** AlertAction to **UIAlertActionStyle.default**

This will basically make the AlertController look like the one in the Armchair screenshots.

Is there a reason it's not like this by default? Thank you!

**Comment by ArturoLee** [comment]
Let me know if you would like me to do a pull for this. Thanks!

**Comment by coneybeare** [comment]
Hm, not sure why this got changed. Sure thing, please test and send a pull request for the change.
