### ISSUE TITLE
'UIAlertView' is deprecated for iOS 9.0+

### ISSUE THREAD

**Issue by arv1989** [UrbanApps/Armchair#106]
When I use the cocoa pod version I get a warning saying 
 /xxx/Armchair/Armchair.framework/Headers/Armchair-Swift.h:170:20: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead

**Comment by arv1989** [comment]
#34

**Comment by coneybeare** [comment]
UIAlertView has already been completely removed from source in master.
