### ISSUE TITLE
Cant figure it out

### ISSUE THREAD

**Issue by NightWarrior** [UrbanApps/Armchair#113]
Hi, its been a few months since i started ios development... so i tried to make a demo app to use Armchair and i cant figure it out about how to use it properly... i checked with the significantEventsUntilPrompt set to 5  and made a button to trigger the Armchair.userDidSignificantEvent with true... so my assumption is that it should keep an internal track and post the alert when 'an' internal counter reaches the set amount of events... Isnt it how it should work? if i put the showPrompt on the button trigger then it shows me an alert... 

So my other thought is that, we will have to use these getters and setters manually to keep track of the values and trigger the showPrompt ourselves.... 

P.S i couldnt find any example codes of a basic work flow with these things... so posting here as an issue.

**Comment by coneybeare** [comment]
You can read the entire Readme, check out the example app, or read through the source to figure it out. Specifically, the [`ratingConditionsHaveBeenMet`](https://github.com/UrbanApps/Armchair/blob/a8c1dfdae562e0aa3521f0813b52b8e6e5c04045/Source/Armchair.swift#L1121) method. Step through that to see what is causing your app to not show the prompt. Most likely, you are using the default `daysUntilPrompt` value and thus it is not showing during your freshly installed test app.
