### ISSUE TITLE
Prompt is showing , but after pressing Rate now button not showing , juts infinite loading

### ISSUE THREAD

**Issue by FaizalMalik** [UrbanApps/Armchair#130]
I have integrated the swift framework and in app delegate initialised Armchari with my app id - 

 Armchair.appID(MY_APP_ID)

***************************
then in a button call i used - 

 Armchair.resetAllCounters()
 Armchair.showPrompt()

App showing the pop and when i click the rate now nothing happens... 

As my app is not published to production, i tried with the Armchair.debugEnabled(true) , still the result is same ..

Could you please tell me how can i see my iTunes page for rating ?

Thanks in advance

**Comment by coneybeare** [comment]
Try stepping through the code and seeing what is happening in your setup.
