### ISSUE TITLE
No module named Armchair

### ISSUE THREAD

**Issue by dhagerty9009** [UrbanApps/Armchair#15]
After following the installation steps exactly, I still cannot `import Armchair`, and Xcode is giving an error - `No such module 'Armchair'`

I'm not really sure where to go from here. I'm using the latest Xcode and latest OSX.

**Comment by ppeelen** [comment]
I am having the same problem with XCode 7.0 and 7.1. Any idea how to solve it? All dependencies are met.

**Comment by coneybeare** [comment]
I finally added cocoapods support so this issue can now be closed.
