### ISSUE TITLE
Error when running on real device

### ISSUE THREAD

**Issue by zenoah01** [UrbanApps/Armchair#16]
Hi,

Just installed the Framework as shown in the video. When running on the simulator it works fine.

When I try and run it on a real iOS device though I the the following errors.

![screen shot 2015-05-08 at 15 34 30](https://cloud.githubusercontent.com/assets/8112447/7538442/c775bf9e-f597-11e4-994c-33a345c0f8cb.png)

![screen shot 2015-05-08 at 15 34 37](https://cloud.githubusercontent.com/assets/8112447/7538450/cfcb690a-f597-11e4-8460-92337f61c4fb.png)

I've tried it on Xcode 6.2 and the latest 6.3 release.

Any ideas?

Thanks,
Anthony

**Comment by Jonovono** [comment]
Honestly, i'd check out iRate for now. I got this same message as you and eventually got it fixed (check out the video. I followed that and fooled around until it worked.). However, when it was time to submit to the app store I got some warnings and couldn't figure it out.

Tried iRate, dragged the files in, removed Armchair and submitted to the app store in a couple of minutes without any issue.

**Comment by coneybeare** [comment]
Don't use iRate, it is not as feature complete as UAAppReviewManager.

**Comment by codertimu** [comment]
@zenoah01 https://stackoverflow.com/questions/24002836/dyld-library-not-loaded-rpath-libswift-stdlib-core-dylib/27109546#27109546
Import the framework in the Embedded Binaries rather than in to the Linked Frameworks and Libraries.
Embedded Binaries are under Projects Settings -> -> General
@coneybeare You might want to update installation procedure.

**Comment by hdaniel** [comment]
I am getting the error below when trying to run on a real iOS device running iOS 9:

`ld: -bundle and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together`

I have tried setting `ENABLE_BITCODE` to No in my project and the Armchair project but still get the same error.  I'm not sure how to resolve this.

**Comment by hdaniel** [comment]
Ok - I got it to work.  It turns out I had only disabled bitcode at the target level but not the project level.  Turning it off for the project and target resolved the error.

**Comment by Alix-MICHEL** [comment]
I have the same issue with ArmchairLocalizable :
```
ld: -bundle and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
```
