### ISSUE TITLE
Swift 2.0 and iOS 9 support

### ISSUE THREAD

**Issue by KyleMay** [UrbanApps/Armchair#19]
Heaps of errors and warnings when opening in Xcode 7 beta.

**Comment by helgetan** [comment]
jep an update is really urgent as iOS9 release is on its way

**Comment by coneybeare** [comment]
I'd be happy to look at any pull requests

**Comment by fabdarice** [comment]
Any timeframe on this?

**Comment by coneybeare** [comment]
I am not actively working on this repo, but will entertain any pull requests

**Comment by fabdarice** [comment]
There's a pull request : https://github.com/UrbanApps/Armchair/pull/20

**Comment by coneybeare** [comment]
Thanks! that flew under my radar
