### ISSUE TITLE
Xcode Errors

### ISSUE THREAD

**Issue by hopkins-matt** [UrbanApps/Armchair#2]
I'm receiving multiple errors while trying to validate my app. Any help would be awesome!
![screen shot 2014-10-13 at 5 29 12 am](https://cloud.githubusercontent.com/assets/3335218/4611521/c3f3c188-52bb-11e4-89d6-7743bf7c5c4f.png)

**Comment by rob7991** [comment]
Hey Matt. I'm having the same problem as you above. I'm using Xcode 6.1.1 and iOS8. Did you ever figure out a solution?
Thanks in advance!

**Comment by hopkins-matt** [comment]
@rob7991 I went ahead and used [UAAppReviewManager](https://github.com/UrbanApps/UAAppReviewManager). I haven't tried Armchair lately, but I'll have to give it another try.

**Comment by coneybeare** [comment]
Sorry guys, i haven't been developing for iOS in many months now, so not sure when I'll get back to have a chance to look at this.

**Comment by rob7991** [comment]
Thanks for the replies guys - I'll let you know if I find a solution.

**Comment by Jonovono** [comment]
Is there a solution for this? I think I have the same issue.
![screen shot 2015-05-18 at 9 02 32 am](https://cloud.githubusercontent.com/assets/775808/7681253/ac6d3d10-fd3c-11e4-8e8f-563069c64b76.png)

**Comment by rob7991** [comment]
@Jonovono Sorry - I haven't had a chance to look at it yet. Will post any solutions I might find, likewise if you do...

**Comment by Alix-MICHEL** [comment]
@Jonovono I have the same issue. I could go through by removing the Armchair.bundle from Copy Bundle Resources, but by doing this I lost the localization feature !

If anyone has a real solution, I am highly interested too.

**Comment by rob7991** [comment]
Hi Alix-Mixhel
I ended up removing the Armchair framework then including the Armchair source code (Armchair.h, Armchair.swift and Localizable strings) in my project. This required a couple of tweaks to Armchair.swift:

- Remove the public func appID
- Create a new public func setAppID(appIDIn: String) which is then called from the app delegate initialize()

Not an ideal solution but it seems to work OK. My app has been approved and is on the store.
Hope this helps.
Rob

**Comment by Alix-MICHEL** [comment]
Thanks, I'll probably try that.
I tried making a local pod from Armchair and it works pretty well but I still have some localization issues to fix.

If the whole project was moved to cocoapods everything would be resolved quickly for everyone...

**Comment by coneybeare** [comment]
Cocoapod finally added! Sorry I took so long guys...
