### ISSUE TITLE
Missing load commands

### ISSUE THREAD

**Issue by hdaniel** [UrbanApps/Armchair#24]
I am getting this error from iTunes Connect after uploading to App Store and I haven't been able to figure out how to resolve it:

"Missing load commands - The executable at '/Payload/Affection Connection.app/Armchair.bundle/Armchair' does not have the necessary load commands. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider."

Any ideas on how to proceed are appreciated!

**Comment by coneybeare** [comment]
That's a strange one. Googling that message yields very few results. Are you using the real version of Xcode?

**Comment by hdaniel** [comment]
Yes, I am using the latest version of Xcode.  I followed the installation instructions in the readme and video to install Armchair, and then removed the info.list file from the archive as described in the wiki to resolve the code signing error.  This is my first iOS app, so my experience tracking this sort of thing down is limited.  

Since I couldn't find anything online similar to my issue I wondered if the problem had something to do with removing the info.plist file, so I went down the path of trying to resolve the code signing entitlement error some other way, but I hit a dead end there.

I wound up getting around the error by manually adding Armchair as a framework directly to my app instead of as a git submodule.  This isn't ideal, of course, but I did spend many hours banging on it with no luck.

**Comment by pavm035** [comment]
Hi,

I'm facing same issue on Xcode7, you got any solution ?

Thanks

**Comment by ZanderDev** [comment]
Hi,I'm facing same issue on Xcode7, you got any solution ?

**Comment by ZanderDev** [comment]
@pavm035 ,Did you get any solution about this problem?

**Comment by pavm035** [comment]
@ZanderDev  Yes i solved this issue by removing versioning from bundle target, where xcode adds agv(apple generic versioning) option which generates *ver.c files during compilation which in turn generates executable file for bundle, and this is the cause of the issue. Hope it helps

Thanks

**Comment by ZanderDev** [comment]
@pavm035 “Yes i solved this issue by removing versioning from bundle target” , what is the meaning of  "removing versioning "?

**Comment by pavm035** [comment]
@ZanderDev  Look at build setting for your bundle target and search for "versioning" set it to None, by default it set to agv

**Comment by ZanderDev** [comment]
@pavm035 Thanks.
