### ISSUE TITLE
Armchair.debugEnabled(true) not working

### ISSUE THREAD

**Issue by lopify** [UrbanApps/Armchair#29]
![keep_xcodeproj](https://cloud.githubusercontent.com/assets/6151348/11571383/eabea4a6-99f3-11e5-8015-6a99eaa653c1.jpg)

I added the corresponding "-DDEBUG" to my Xcode project but still not working.

Thanks!

**Comment by lopify** [comment]
My bad, never mind, I had to add that flag to the pod project :S

**Comment by Domsware** [comment]
It seems you found answer for CocoaPods. But what about Carthage installation?

**Comment by Rubicoin** [comment]
no idea man :(

**Comment by jlubeck** [comment]
@lopify how do you add it to the pod project without being overwritten everytime you do a pod install?
