### ISSUE TITLE
Support for Prebuilt frameworks to use with Carthage

### ISSUE THREAD

**Issue by johnnye** [UrbanApps/Armchair#31]
It would be nice if for each tagged release you enabled pre built frameworks also - this would enable Carthage users to have faster build times. 

See https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file for details on how to implement this. (it's pretty easy)

**Comment by coneybeare** [comment]
I am not a Carthage user, but if you would like to package them up, test it, and submit a pull request, I would take a look and see about merging into master.

**Comment by johnnye** [comment]
Not much code to add I built these from the head of the master - but I think this is close to the 0.1.1 release.

**Comment by johnnye** [comment]
I'm closing this issue, it all seems 👍🏼.
