### ISSUE TITLE
UIAlertView is deprecated

### ISSUE THREAD

**Issue by jlaws** [UrbanApps/Armchair#34]
You should use UIAlertController instead.

**Comment by coneybeare** [comment]
I will entertain a pull request that maintains backwards compatibility.

**Comment by phimage** [comment]
Maybe change only the default value of `usesAlertController` to `true`
@jlaws just set `usesAlertController` to true for the moment

**Comment by coneybeare** [comment]
I like that idea of setting the default to true based on `operatingSystemVersion`

**Comment by jlaws** [comment]
Finally got around to looking at this thread again.  My concern was the build warning:

`Armchair-Swift.h:130:20: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead`

Considering that [95%](https://developer.apple.com/support/app-store/) or [97.5%](https://mixpanel.com/trends/#report/ios_9) of devices are running iOS 8+ it is probably save to make the min target for the library iOS 8 and use alert controllers exclusively.  Just create a fork and leave the old cocoapods for people who want to target earlier versions.  

Another option is to suppress the warning inside the library.

**Comment by tbaranes** [comment]
I agree with @jlaws solution. If you really don't want to target only iOS8+, you should suppress that warning directly in the library.

**Comment by coneybeare** [comment]
I'd consider a pull request of that warning suppression

**Comment by virl** [comment]
Please fix that warning. Also iOS8+ only is fine.

**Comment by KMessina1** [comment]
This really needs to be fixed, every time I do a clean build it gives me the warning. At this point, its pretty annoying. I moved to this library so that it would be modern and a Swift solution to Appirater.

**Comment by coneybeare** [comment]
@KMessina1 I will entertain any pull request surpassing the warning, please feel free to contribute.

**Comment by arv1989** [comment]
@coneybeare @jlaws any update on this? It's still the same.

**Comment by coneybeare** [comment]
UIAlertView has already been completely removed from source in master.
