### ISSUE TITLE
Debug message

### ISSUE THREAD

**Issue by Arti3DPlayer** [UrbanApps/Armchair#40]
I added -DDebug flag to my project.

![screen shot 2016-03-30 at 16 19 49](https://cloud.githubusercontent.com/assets/3278913/14143327/5feb17cc-f693-11e5-88c2-04d443f9d8a3.png)

Then in code did:

```
#if Debug
     Armchair.debugEnabled(true)
 #endif
```

But always get message:
```
[Armchair] Debug is disabled on release builds.
[Armchair]   If you really want to enable debug mode,
[Armchair]   add "-DDebug" to your  Swift Compiler - Custom Flags
[Armchair]   section in the target's build settings for release
```

Source:
```
public func debugEnabled(debugEnabled: Bool) {
#if Debug
    Manager.defaultManager.debugEnabled = debugEnabled
#else
    print("[Armchair] Debug is disabled on release builds.")
    print("[Armchair]   If you really want to enable debug mode,")
    print("[Armchair]   add \"-DDebug\" to your  Swift Compiler - Custom Flags")
    print("[Armchair]   section in the target's build settings for release")
#endif
}
```

**Comment by coneybeare** [comment]
You have to add the flag to the pod project

**Comment by Arti3DPlayer** [comment]
How to do this ?

**Comment by Arti3DPlayer** [comment]
Ah, ok i understand

**Comment by nchodelski** [comment]
@Arti3DPlayer I'm going thru different areas trying to add the -DDebug flag and still havent worked it out. Could you explain how you figured this out? 

Ideally if you can post a picture of xcode showing the area of the project and the area of the build settings where you find and add the flag, that would be most helpful.

**Comment by Arti3DPlayer** [comment]
@nchodelski you were close.

https://cloud.githubusercontent.com/assets/10591026/15378457/82b39e72-1d18-11e6-9fe2-509216701da1.png

select Armchair project and add `-DDebug flag here`

**Comment by nchodelski** [comment]
Thanks for the advice. I tried setting -DDEBUG specifically for the Armchair target within the Pods Project as you described and I still have the same result. Its weird. I made an issue about this...maybe I can get to the bottom of it.

For now I worked around it by modifying Armchair.swift to think it's in debug mode all the time....hack but it works great! Lol.

**Comment by Arti3DPlayer** [comment]
@nchodelski i noticed that you write `-DDEBUG` with uppercase. But it should `-DDebug`. Method that i showed you works for me and other guys.

**Comment by nchodelski** [comment]
Wow, that was it. When i used "DDebug" Armchair debug mode worked perfectly!   I'm amazed it was actually such a simple thing. I had been using it as "DDEBUG" in capitals because in every example I saw of how to add the flag, it was always written or shown as "-DDEBUG" in all caps.   I didn't realise it was case sensitive.

Thanks very much for that tip!!
