### ISSUE TITLE
Remind button always shows if remindButtonTitle is set

### ISSUE THREAD

**Issue by JagCesar** [UrbanApps/Armchair#45]
Hey!

Let me start of by thanking you for writing this. Much love.

I ran across a bug and wanted to report it, not sure if I'm missing something. If it's a bug I'll gladly fix it and send a PR.

If `daysBeforeReminding` is set to zero and `remindButtonTitle` is set, the remind Button appears in the rate pop up. The bug seems to be in [showsRemindButton()](https://github.com/UrbanApps/Armchair/blob/master/Source/Armchair.swift#L1136)

`showsRemindButton()` should return false if `daysBeforeReminding` is set to zero.

**Comment by coneybeare** [comment]
I agree, that looks like an oversight, considering we do a similar check [here](https://github.com/UrbanApps/Armchair/blob/master/Source/Armchair.swift#L765). I would entertain a pull request fixing it.

**Comment by JagCesar** [comment]
Sweet. I'm on it.
