### ISSUE TITLE
Way to reset all counters

### ISSUE THREAD

**Issue by fotiDim** [UrbanApps/Armchair#49]
Is there a way to manually reset all counters (uses, significantEvents, etc)? I don't want to change the thresholds, just reset all counters.

**Comment by coneybeare** [comment]
The app automatically resets on new versions. There is no way to manually trigger this, but I would entertain a pull request to do so. You would have to pull [this](https://github.com/UrbanApps/Armchair/blob/master/Source/Armchair.swift#L977) block out and put it into a new public method.

**Comment by Navideck-fotis** [comment]
PR #51 is up
