### ISSUE TITLE
Carthage: issue with error "dyld: Symbol not found: __TMPdCSs18_HeapBufferStorage"

### ISSUE THREAD

**Issue by stefat** [UrbanApps/Armchair#64]
Environment references:
Carthage version: 0.6.12
xcodebuild -version: Xcode 7.3 Build version 7D175
 --no-build? no
 --no-use-binaries? no
 --use-submodules? no

Cartfile:
github "UrbanApps/Armchair"
Cartfile resolved:
github "UrbanApps/Armchair" "0.1.2"

Carthage Output:
<..>$ carthage update
*** Fetching Armchair
*** Downloading Armchair.framework binary at "0.1.2"
*** xcodebuild output can be found in /var/folders/xx/zhysw05j1pn9jw3vypwb3rrw0000gn/T/carthage-xcodebuild.ky9ANZ.log```

Armchair.framework is in Xcode in sections:
• Link Binary With libraries
• Copy Bundle Resources
• Embed Frameworks, with Code Sign On Copy switched on
• Build Rules (SCRIPT: /usr/local/bin/carthage copy-frameworks for source files : $(SRCROOT)/Carthage/Build/iOS/Armchair.framework. The folder exists with the framework in)
#####################################################################
I was having at first an issue with an 'image not found' message as I missed to add the framework library Armchair in the Embed Frameworks section of Build Phases (Xcode 7.3). 
Done that I was happily waiting the sw run but I also got an unexpected 'symbol not found' error message:
`dyld: Symbol not found: __TMPdCSs18_HeapBufferStorage Referenced from: /Users/<..>/Library/Developer/Xcode/DerivedData/JotAgenda-gazubqkikzwwstckckciztnqufsb/Build/Products/Debug-iphonesimulator/Armchair.framework/Armchair Expected in: /Users/<..>/Library/Developer/CoreSimulator/Devices/C61B939F-2F90-4314-AA8C-B36C15E2D8C0/data/Containers/Bundle/Application/058F8711-F90C-48FC-A7B4-31D0298D97B9/JotAgenda.app/Frameworks/libswiftCore.dylib in /Users/<..>/Library/Developer/Xcode/DerivedData/JotAgenda-gazubqkikzwwstckckciztnqufsb/Build/Products/Debug-iphonesimulator/Armchair.framework/Armchair 
`
Am I missing something else? Is it an issue related to the framework generation ? 
I also attach the Carthage zipped folder coming out the update command.
BTW: the checkout folder is not generated. 
Is that correct ?.
Thank you for any help.
Stefat
#######################################################################
[Carthage.zip](https://github.com/UrbanApps/Armchair/files/318269/Carthage.zip)

**Comment by stefat** [comment]
Edit:
I rebuilt the binary using the command `carthage update --no-use-binaries.`
The Checkout folder becomes now generated but the Xcode error is still there: 
`dyld: Symbol not found: __TMPdCSs18_HeapBufferStorage`

Same as before the Armchair.framework is in Xcode in sections:
• Link Binary With libraries
• Copy Bundle Resources
• Embed Frameworks, with Code Sign On Copy switched on
• Build Rules (SCRIPT: /usr/local/bin/carthage copy-frameworks for source files : $(SRCROOT)/Carthage/Build/iOS/Armchair.framework. The folder exists with the framework in)

Any clue ?

**Comment by coneybeare** [comment]
https://github.com/Carthage/Carthage/issues/1044
