### ISSUE TITLE
Armchair can show automatic prompt alert to rating app?

### ISSUE THREAD

**Issue by kakashysen** [UrbanApps/Armchair#65]
I want to know if Armchair show alert to rate automatic when configure the `Armchair.significantEventsUntilPrompt(2)` and `Armchair.userDidSignificantEvent(true)`. Or I need to call `Armchair.showPrompt()` to show alert?

**Comment by coneybeare** [comment]
You need 2 significant events to show, and it would also have to be the default time after installation. I would suggest reading through the default values in the readme.
