### ISSUE TITLE
Trouble with versions ?

### ISSUE THREAD

**Issue by dirkbartels14050** [UrbanApps/Armchair#70]
I installed Armchair via cocoapods. The installation worked fine. I do have a couple of issues. It seems that the version that is installed is not the latest version. Example

In the documentation is referred to this method:

Armchair.ratingConditionsHaveBeenMet() -> Bool

This method is 'private' in the delivered code and therefore not reachable. 

Also, the KeyDeclinedToRate returns 'true'. This was never set, how is that possible ? It seems to me that this state does not allow to show the rating prompt.

Any comments / advice ?

**Comment by coneybeare** [comment]
Try installing from head

**Comment by dirkbartels14050** [comment]
Thanks. That worked. Would be great if you guys post a new version that can be installed via cocoapods
