### ISSUE TITLE
Check for Simulator not working

### ISSUE THREAD

**Issue by OliverZiegler** [UrbanApps/Armchair#78]
I think beginning with iOS 9 this check

`UIDevice.current.model.range(of: "Simulator") != nil`

will never succeed and so current developers will not get console logs and possibly wonder why nothing happens when starting to rate.

Possible alternate methods are stated [here](http://stackoverflow.com/a/24869607/2408916)

**Comment by coneybeare** [comment]
Pull requests accepted!

**Comment by OliverZiegler** [comment]
Here you are. And for both, master and swift3 branch ;)
