### ISSUE TITLE
iOS 10.3 API

### ISSUE THREAD

**Issue by jackcsk** [UrbanApps/Armchair#85]
Just writing to find out if Armchair plans to provide transparent support for iOS 10.3

i.e. call SKStoreReviewController's  `requestReview()` method on iOS 10.3, and use current routine on iOS 10.2 or below

**Comment by coneybeare** [comment]
This is definitely something I will look into as more details emerge.

**Comment by jlaws** [comment]
+1

**Comment by jlaws** [comment]
10.3 is out
https://developer.apple.com/reference/storekit/skstorereviewcontroller

**Comment by jlaws** [comment]
For those that don't want to wait for the library to add support, you can do this where you setup Armchair:

    Armchair.shouldPromptClosure { info -> Bool in
      if #available(iOS 10.3, *) {
        SKStoreReviewController.requestReview()
        return false
      } else {
        return true
      }
    }

**Comment by ari3l** [comment]
Took a shot at implementing this. 
Just made a [PR](https://github.com/UrbanApps/Armchair/pull/92) based off @jlaws code.

**Comment by coneybeare** [comment]
This needs to be opt-in, so previous expected behavior is not altered. Please add a public var to enable this logic and I will merge in.

**Comment by ari3l** [comment]
@coneybeare 
I don't understand. The feature is already opt-in. By default no behavior is altered. To use the new review prompt, simply do this:
`      Armchair.appID("xxxxxxx")
        Armchair.useStoreKitReviewPrompt(true) // This alters the default behavior -- default is false
`

**Comment by coneybeare** [comment]
Yes you're right. Sorry, I misread your comment earlier as in future tense. I just reviewed your PR, looks great.

**Comment by umekun123** [comment]
I cannot see Armchair.useStoreKitReviewPrompt(true)  on 4.4, is it disabled for some reason?

**Comment by coneybeare** [comment]
We have no version 4.4, are you sure you are looking at the right pod?

**Comment by umekun123** [comment]
Sorry, my mistake.  I was using the cocoapod latest version and it didn't support the latest one who supports useStoreKitReviewPrompt.  I simply copied the latest codes to my pods file and it works fine now.  It would be great if the latest pods will be udpated to support the latest version. :)
