### ISSUE TITLE
Only using significant events

### ISSUE THREAD

**Issue by nickoneill** [UrbanApps/Armchair#9]
Hi there,

Say I only want to use the significant event tracker and disable the `daysUntilPrompt` and `usesUntilPrompt` notifications. Does setting these to 0 disable similarly to the remind functionality?

**Comment by coneybeare** [comment]
No they don't, but if you don't ever want to show a prompt, implement a `ArmchairShouldPromptClosure` to stop it from ever showing, or set those values to their max.
````
