### ISSUE TITLE
Armchair.showPrompt() shows without counting significant Events

### ISSUE THREAD

**Issue by sergeydi** [UrbanApps/Armchair#90]
Hi,
My AppDelegate.swift:
    
     Armchair.appID("myAppID")
     Armchair.debugEnabled(true)
     Armchair.significantEventsUntilPrompt(200)

on ViewController:

    Armchair.showPrompt()
    or
    Armchair.showPromptIfNecessary()

Delete app from simulator, Execute app and receive proposal to rate app. Is it correct, or I make some mistake?

**Comment by coneybeare** [comment]
`DebugEnabled` will show the prompt every time by tricking the library into thinking all conditions have been met. It is meant for testing.
