### ISSUE TITLE
Using the store kit review prompt will ask for reviews forever if the user taps "Not Now"

### ISSUE THREAD

**Issue by ari3l** [UrbanApps/Armchair#93]
[SKStoreReviewController](https://developer.apple.com/reference/storekit/skstorereviewcontroller) doesn't have an API that tells us if the user submits a review, as a result, if rating conditions are met the library will constantly ask for a review.

I fixed this locally by setting UserDefaults to mark the current version as reviewed when calling `requestReview()`. This means that the user will see the review prompt once per version, regardless if the user rates or not.

I can submit a PR with the fix, but I'm not sure if that would be the correct approach. Let me know what you guys think!

**Comment by coneybeare** [comment]
I think your approach is reasonable. Thanks for catching that
