### ISSUE TITLE
Armchair isn't working with fast release cycles

### ISSUE THREAD

**Issue by blixt** [UrbanApps/Armchair#96]
When releasing a new version for the app every 2-3 days, Armchair will either need a condition that triggers too soon, or not at all.

The reason for this is that `tracksNewVersions = true` will reset the values every time the app is updated (every 2-3 days, so we have to lower the threshold = too soon) and setting it to `false` will just stop tracking altogether once the user updates the app.

Ideally there'd be an option to track significant events across multiple app versions so that the thresholds can be set higher even if the user updates their app often.

**Comment by coneybeare** [comment]
You could use the hooks to build you own logic on when to show the prompt rather than use the default delineator of a new version number
